name: End-to-end tests
on: [push]
jobs:
  cypress-run-electron:
    runs-on: ubuntu-20.04
    name: E2E cyp run on Electron
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress core tests
      - name: Runnning E2E regression test suite with cypress...
        uses: cypress-io/github-action@v2
  cypress-run-chrome:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: E2E cyp run on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
  firefox-run-firefox:
    name: E2E cyp run on Firefox
    # should include Firefox browser install
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Firefox
        uses: ./
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-firefox
          path: screenshots/firefox

      - run: npx image-size screenshots/**/*.png
